import { useState } from "react";
import { Download, Loader2, FileDown } from "lucide-react";
import { cn } from "@/lib/utils";

export interface PptxSlide {
  tag?: string;
  title: string;
  subtitle?: string;
  body?: string;
  footer?: string;
}

export interface PptxExportProps {
  filename?: string;
  deckTitle: string;
  brandName?: string;
  slides: PptxSlide[];
  buttonLabel?: string;
  className?: string;
  variant?: "button" | "card";
}

const BRAND_COLOR = "6C3BF5";
const DARK = "18181B";
const LIGHT = "FAFAFA";
const MUTED = "71717A";

async function buildAndDownload(props: PptxExportProps) {
  const pptxgen = (await import("pptxgenjs")).default;
  const pres = new pptxgen();
  pres.layout = "LAYOUT_WIDE";
  pres.title = props.deckTitle;

  const W = 13.33;

  // ── Title slide ─────────────────────────────────────────────────────────────
  const title = pres.addSlide();
  title.background = { color: DARK };

  title.addShape(pres.ShapeType.rect, {
    x: 0, y: 0, w: 0.18, h: 7.5,
    fill: { color: BRAND_COLOR },
    line: { type: "none" },
  });

  title.addText(props.brandName ?? "Zuri AI", {
    x: 0.5, y: 1.8, w: W - 1, h: 0.7,
    fontSize: 16, color: BRAND_COLOR, bold: true,
    fontFace: "Calibri",
  });

  title.addText(props.deckTitle, {
    x: 0.5, y: 2.6, w: W - 1, h: 1.6,
    fontSize: 44, color: LIGHT, bold: true,
    fontFace: "Calibri", wrap: true,
  });

  title.addText("Generated by Zuri AI  ·  zuriaiapp.com", {
    x: 0.5, y: 6.8, w: W - 1, h: 0.4,
    fontSize: 11, color: "555577",
    fontFace: "Calibri",
  });

  // ── Content slides ───────────────────────────────────────────────────────────
  for (const slide of props.slides) {
    const s = pres.addSlide();
    s.background = { color: LIGHT };

    s.addShape(pres.ShapeType.rect, {
      x: 0, y: 0, w: W, h: 0.08,
      fill: { color: BRAND_COLOR },
      line: { type: "none" },
    });

    let cursorY = 0.35;

    if (slide.tag) {
      s.addText(slide.tag.toUpperCase(), {
        x: 0.55, y: cursorY, w: W - 1.1, h: 0.38,
        fontSize: 10, color: BRAND_COLOR, bold: true,
        fontFace: "Calibri",
      });
      cursorY += 0.42;
    }

    s.addText(slide.title, {
      x: 0.55, y: cursorY, w: W - 1.1, h: 1.1,
      fontSize: 26, color: DARK, bold: true,
      fontFace: "Calibri", wrap: true,
    });
    cursorY += 1.15;

    if (slide.subtitle) {
      s.addText(slide.subtitle, {
        x: 0.55, y: cursorY, w: W - 1.1, h: 0.55,
        fontSize: 14, color: BRAND_COLOR, bold: false,
        fontFace: "Calibri",
      });
      cursorY += 0.6;
    }

    if (slide.body) {
      s.addText(slide.body, {
        x: 0.55, y: cursorY, w: W - 1.1, h: 7.5 - cursorY - 0.65,
        fontSize: 13, color: DARK, wrap: true,
        fontFace: "Calibri", valign: "top",
        paraSpaceAfter: 6,
      });
    }

    if (slide.footer) {
      s.addText(slide.footer, {
        x: 0.55, y: 7.1, w: W - 1.1, h: 0.3,
        fontSize: 9, color: MUTED,
        fontFace: "Calibri",
      });
    }

    s.addText("zuriaiapp.com", {
      x: W - 2, y: 7.1, w: 1.78, h: 0.3,
      fontSize: 9, color: MUTED, align: "right",
      fontFace: "Calibri",
    });
  }

  const name = props.filename ?? props.deckTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  await pres.writeFile({ fileName: `${name}.pptx` });
}

export function PptxExport({ className, variant = "button", buttonLabel = "Download as PowerPoint", ...props }: PptxExportProps) {
  const [loading, setLoading] = useState(false);

  async function handleClick() {
    setLoading(true);
    try {
      await buildAndDownload(props);
    } catch (e) {
      console.error("PPTX export failed", e);
    } finally {
      setLoading(false);
    }
  }

  if (variant === "card") {
    return (
      <button
        onClick={handleClick}
        disabled={loading || props.slides.length === 0}
        className={cn(
          "w-full flex items-center gap-3 px-4 py-3.5 rounded-xl border-2 border-dashed border-border hover:border-primary/50 hover:bg-primary/5 transition-all text-left group disabled:opacity-50 disabled:cursor-not-allowed",
          className
        )}
      >
        <div className="h-10 w-10 rounded-xl bg-primary/10 flex items-center justify-center shrink-0 group-hover:bg-primary/20 transition-colors">
          {loading ? <Loader2 className="h-5 w-5 text-primary animate-spin" /> : <FileDown className="h-5 w-5 text-primary" />}
        </div>
        <div>
          <p className="text-sm font-semibold text-foreground">{buttonLabel}</p>
          <p className="text-xs text-muted-foreground mt-0.5">
            {loading ? "Building your deck..." : `${props.slides.length} slide${props.slides.length !== 1 ? "s" : ""} · Free · No account needed`}
          </p>
        </div>
      </button>
    );
  }

  return (
    <button
      onClick={handleClick}
      disabled={loading || props.slides.length === 0}
      className={cn(
        "inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border bg-card hover:bg-muted text-sm font-semibold text-foreground transition-colors disabled:opacity-50",
        className
      )}
    >
      {loading ? <Loader2 className="h-4 w-4 animate-spin text-primary" /> : <Download className="h-4 w-4 text-primary" />}
      {loading ? "Building..." : buttonLabel}
    </button>
  );
}

// ── Helpers to build slide arrays from common data ───────────────────────────

export function buildContentPlanSlides(
  posts: Array<{ day: number; platform: string; contentType: string; topic: string; angle?: string; caption?: string }>
): PptxSlide[] {
  const intro: PptxSlide = {
    title: "Content Plan Overview",
    subtitle: `${posts.length} posts planned`,
    body: posts
      .slice(0, 12)
      .map(p => `Day ${p.day}  |  ${p.platform}  |  ${p.contentType}  -  ${p.topic}`)
      .join("\n"),
  };

  const detail: PptxSlide[] = posts.map(p => ({
    tag: `Day ${p.day} · ${p.platform} · ${p.contentType}`,
    title: p.topic,
    subtitle: p.angle ?? undefined,
    body: p.caption ?? undefined,
    footer: `${p.platform} · ${p.contentType}`,
  }));

  return [intro, ...detail];
}

export function buildBulkPlanSlides(
  planName: string,
  items: Array<{ platform: string; contentTheme: string; suggestedDate: string; captionDraft?: string | null }>
): PptxSlide[] {
  const generated = items.filter(i => i.captionDraft);
  const intro: PptxSlide = {
    title: planName,
    subtitle: `${generated.length} of ${items.length} posts with captions`,
    body: items
      .slice(0, 14)
      .map(i => `${i.suggestedDate}  |  ${i.platform}  -  ${i.contentTheme}`)
      .join("\n"),
  };

  const detail: PptxSlide[] = generated.map(i => ({
    tag: `${i.suggestedDate} · ${i.platform}`,
    title: i.contentTheme,
    body: i.captionDraft ?? undefined,
    footer: `${i.platform} · ${i.suggestedDate}`,
  }));

  return [intro, ...detail];
}
