import { PublicNav, PublicFooter } from "@/components/public-nav";

const Z_BG = "#0C0A08";
const Z_SURFACE = "#141210";
const Z_TEXT = "#F5F0EB";
const Z_MUTED = "rgba(245,240,235,0.5)";
const Z_FAINT = "rgba(245,240,235,0.3)";
const Z_BORDER = "rgba(255,255,255,0.06)";
const Z_ORANGE = "#E05C2A";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 20, fontWeight: 700, color: Z_TEXT, marginBottom: 12, letterSpacing: "-0.3px" }}>{title}</h2>
      <div style={{ color: Z_MUTED, fontSize: 15, lineHeight: 1.75 }}>{children}</div>
    </div>
  );
}

export default function Terms() {
  return (
    <div style={{ background: Z_BG, minHeight: "100vh", color: Z_TEXT, fontFamily: "Inter, system-ui, sans-serif" }}>
      <PublicNav />

      <main style={{ maxWidth: 760, margin: "0 auto", padding: "60px 24px 100px" }}>
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 13, color: Z_FAINT, marginBottom: 12, textTransform: "uppercase", letterSpacing: 1 }}>Legal</p>
          <h1 style={{ fontSize: "clamp(28px, 4vw, 42px)", fontWeight: 800, letterSpacing: "-1.5px", marginBottom: 12 }}>
            Terms of <span style={{ color: Z_ORANGE }}>Service</span>
          </h1>
          <p style={{ color: Z_MUTED, fontSize: 15 }}>Last updated: April 15, 2026</p>
        </div>

        <div style={{ background: Z_SURFACE, border: `1px solid ${Z_BORDER}`, borderRadius: 12, padding: "20px 24px", marginBottom: 40 }}>
          <p style={{ color: Z_MUTED, fontSize: 14, lineHeight: 1.7 }}>
            These Terms of Service govern your access to and use of Zuri AI. Please read them carefully. By creating an account or using our services, you agree to be bound by these terms.
          </p>
        </div>

        <Section title="1. The Service">
          <p>Zuri AI is an AI-powered marketing content platform designed for African businesses and global emerging markets. We provide tools to generate social media content, marketing copy, content plans, and visual assets using artificial intelligence.</p>
        </Section>

        <Section title="2. Account Eligibility & Responsibility">
          <ul style={{ paddingLeft: 20 }}>
            <li style={{ marginBottom: 6 }}>You must be at least 18 years old to use Zuri AI</li>
            <li style={{ marginBottom: 6 }}>You are responsible for maintaining the security of your account and password</li>
            <li style={{ marginBottom: 6 }}>You are responsible for all activity that occurs under your account</li>
            <li style={{ marginBottom: 6 }}>You must provide accurate information during registration and keep it up to date</li>
          </ul>
        </Section>

        <Section title="3. Acceptable Use">
          <p style={{ marginBottom: 10 }}>You agree to use Zuri AI only for lawful purposes. You must not:</p>
          <ul style={{ paddingLeft: 20 }}>
            <li style={{ marginBottom: 6 }}>Generate content that is illegal, abusive, defamatory, or infringes on third-party rights</li>
            <li style={{ marginBottom: 6 }}>Use the platform to send unsolicited communications or spam</li>
            <li style={{ marginBottom: 6 }}>Attempt to reverse-engineer, scrape, or copy the platform</li>
            <li style={{ marginBottom: 6 }}>Resell access to Zuri AI without prior written consent</li>
            <li style={{ marginBottom: 6 }}>Use the platform in a way that could damage, disable, or impair our infrastructure</li>
          </ul>
        </Section>

        <Section title="4. AI-Generated Content">
          <p style={{ marginBottom: 10 }}>All content generated by Zuri AI is produced by third-party AI models. You understand that:</p>
          <ul style={{ paddingLeft: 20 }}>
            <li style={{ marginBottom: 6 }}>AI-generated content may sometimes be inaccurate, incomplete, or unsuitable for your needs</li>
            <li style={{ marginBottom: 6 }}>You are responsible for reviewing, editing, and approving all content before publishing</li>
            <li style={{ marginBottom: 6 }}>Zuri AI makes no warranties regarding the accuracy or fitness of generated content</li>
            <li style={{ marginBottom: 6 }}>Ownership of AI-generated content is granted to you upon generation, subject to these terms</li>
          </ul>
        </Section>

        <Section title="5. Subscriptions & Payments">
          <p style={{ marginBottom: 10 }}>Zuri AI offers free and paid subscription plans:</p>
          <ul style={{ paddingLeft: 20 }}>
            <li style={{ marginBottom: 6 }}>Payments are processed securely through Paystack</li>
            <li style={{ marginBottom: 6 }}>Subscriptions renew automatically unless cancelled before the renewal date</li>
            <li style={{ marginBottom: 6 }}>Prices are displayed in Nigerian Naira (NGN) and US Dollars (USD)</li>
            <li style={{ marginBottom: 6 }}>Refund requests are reviewed case by case. Contact us within 7 days of charge for assistance</li>
          </ul>
        </Section>

        <Section title="6. Intellectual Property">
          <p>Zuri AI and all associated software, design, and branding are the intellectual property of Zuri AI. The Zuri AI name, logo, and product design may not be used without express written permission. Content you create using Zuri AI belongs to you.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>To the maximum extent permitted by applicable law, Zuri AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the service. Our total liability shall not exceed the amount you paid to us in the 3 months prior to the claim.</p>
        </Section>

        <Section title="8. Termination">
          <p>We reserve the right to suspend or terminate your account if you violate these terms. You may also close your account at any time through your account settings. Upon termination, your right to use Zuri AI ceases immediately.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the courts of Lagos State, Nigeria.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>We may modify these Terms at any time. We will notify you of material changes by email or in-app notice at least 14 days before they take effect. Continued use of the service constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="11. Contact Us">
          <p>For questions about these Terms, reach us at:</p>
          <div style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 8 }}>
            <a href="mailto:hello@zuriai.africa" style={{ color: Z_ORANGE, textDecoration: "none", fontSize: 15 }}>hello@zuriai.africa</a>
            <a href="tel:+2348027244825" style={{ color: Z_MUTED, textDecoration: "none", fontSize: 15 }}>+234 802 724 4825</a>
          </div>
        </Section>
      </main>

      <PublicFooter />
    </div>
  );
}
