import { db } from "../index";
import { calendarEventsTable } from "../schema/calendar_events";

const events = [
  // ─── NIGERIAN PUBLIC HOLIDAYS (fixed) ───────────────────────────────────────
  {
    name: "New Year's Day",
    eventType: "public_holiday",
    month: 1, day: 1,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "EG", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Fresh start energy - new goals, new year offers, motivational brand messages. Very high engagement window.",
    leadDays: 5,
  },
  {
    name: "Valentine's Day",
    eventType: "commercial_event",
    month: 2, day: 14,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate love - couple offers, gift bundles, romance-themed campaigns. Works for every product category with the right angle.",
    leadDays: 7,
  },
  {
    name: "International Women's Day",
    eventType: "awareness_day",
    month: 3, day: 8,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "EG", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate Nigerian and African women - female customers, staff, founders. Share brand values around inclusion and empowerment.",
    leadDays: 7,
  },
  {
    name: "Good Friday",
    eventType: "public_holiday",
    month: 4, day: 18,
    isFloating: true,
    floatingRule: "Friday before Easter Sunday - typically March or April",
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: ["Christian"],
    contentAngle: "Reflective, reverent tone. Acknowledge the day respectfully. Avoid heavy promotional content - use brand story or values messaging.",
    leadDays: 3,
  },
  {
    name: "Easter Sunday",
    eventType: "public_holiday",
    month: 4, day: 20,
    isFloating: true,
    floatingRule: "First Sunday after the first full moon after March 21 - typically March or April",
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: ["Christian"],
    contentAngle: "Joy, renewal, family celebration. Post-Easter sales promotions work well. Family-friendly messaging and gift offers.",
    leadDays: 5,
  },
  {
    name: "Easter Monday",
    eventType: "public_holiday",
    month: 4, day: 21,
    isFloating: true,
    floatingRule: "Day after Easter Sunday",
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: ["Christian"],
    contentAngle: "Extended Easter celebration - deals and offers, family outing content, post-holiday recap.",
    leadDays: 2,
  },
  {
    name: "Workers' Day (Labour Day)",
    eventType: "public_holiday",
    month: 5, day: 1,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate your team and customers. Appreciation posts, staff spotlight, behind-the-scenes of your business. Good for employer brand content.",
    leadDays: 3,
  },
  {
    name: "Mother's Day (Nigeria)",
    eventType: "commercial_event",
    month: 5, day: 11,
    isFloating: true,
    floatingRule: "Second Sunday of May",
    countries: ["NG", "GH"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate mothers - gift guides, appreciation posts, special offers. One of the highest-spend shopping moments of the year in Nigeria.",
    leadDays: 10,
  },
  {
    name: "Eid al-Fitr (End of Ramadan)",
    eventType: "public_holiday",
    month: 4, day: 1,
    isFloating: true,
    floatingRule: "End of Ramadan - lunar calendar, moves each year. Typically March-April. Always verify actual date.",
    countries: ["NG", "KE", "SN", "EG"],
    continent: "Africa",
    religions: ["Muslim"],
    contentAngle: "Eid Mubarak messaging. Celebratory, joyful tone. Gift offers, fashion, food. Massive buying moment - launch promotions 5 days before Eid.",
    leadDays: 7,
  },
  {
    name: "Eid al-Adha (Eid Kabir / Sallah)",
    eventType: "public_holiday",
    month: 6, day: 7,
    isFloating: true,
    floatingRule: "70 days after Eid al-Fitr - lunar calendar, moves each year. Typically May-July. Always verify actual date.",
    countries: ["NG", "KE", "SN", "EG"],
    continent: "Africa",
    religions: ["Muslim"],
    contentAngle: "Eid Kabir / Big Sallah - the bigger of the two Eids in Nigeria. Family gatherings, rams, new clothes. High consumer spend. Patriotic and cultural tone works well.",
    leadDays: 7,
  },
  {
    name: "Democracy Day (Nigeria)",
    eventType: "public_holiday",
    month: 6, day: 12,
    isFloating: false,
    countries: ["NG"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate Nigerian democracy and resilience. Brand values content - patriotic but not political. Good for 'made in Nigeria' or 'proudly Nigerian' messaging.",
    leadDays: 3,
  },
  {
    name: "Father's Day",
    eventType: "commercial_event",
    month: 6, day: 15,
    isFloating: true,
    floatingRule: "Third Sunday of June",
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate fathers - gift guides, appreciation posts, family content. Complements Mother's Day campaigns. Good for lifestyle, fashion, and tech brands.",
    leadDays: 7,
  },
  {
    name: "Mawlid al-Nabi (Prophet's Birthday)",
    eventType: "public_holiday",
    month: 9, day: 5,
    isFloating: true,
    floatingRule: "12th of Rabi al-Awwal in the Islamic calendar - moves each year. Verify actual date annually.",
    countries: ["NG", "KE", "SN", "EG"],
    continent: "Africa",
    religions: ["Muslim"],
    contentAngle: "Respectful and warm acknowledgement. Keep messaging inclusive and spiritual. Not a heavy promotional day - use values-based content.",
    leadDays: 3,
  },
  {
    name: "Nigeria Independence Day",
    eventType: "public_holiday",
    month: 10, day: 1,
    isFloating: false,
    countries: ["NG"],
    continent: "Africa",
    religions: [],
    contentAngle: "Nigeria at 60+ - national pride content. Green-white-green colour themes. 'Proudly Nigerian' product highlights, origin stories, team appreciation. Very high engagement on this day.",
    leadDays: 7,
  },
  {
    name: "Children's Day (Nigeria)",
    eventType: "public_holiday",
    month: 5, day: 27,
    isFloating: false,
    countries: ["NG"],
    continent: "Africa",
    religions: [],
    contentAngle: "Family brands, education brands, parenting content. Spotlight children in your customer community. Heartwarming storytelling works well.",
    leadDays: 3,
  },
  {
    name: "Black Friday",
    eventType: "commercial_event",
    month: 11, day: 28,
    isFloating: true,
    floatingRule: "Fourth Friday of November",
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Biggest Nigerian e-commerce moment of the year. Build anticipation from two weeks before. Flash sales, countdown posts, email/WhatsApp campaigns. High competition - start early.",
    leadDays: 14,
  },
  {
    name: "Christmas Day",
    eventType: "public_holiday",
    month: 12, day: 25,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: ["Christian"],
    contentAngle: "Season's greetings - warm, celebratory tone. Gift guides, last-minute offers, year-in-review content. One of the biggest spending periods in Nigeria.",
    leadDays: 14,
  },
  {
    name: "Boxing Day",
    eventType: "public_holiday",
    month: 12, day: 26,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Post-Christmas deals, clearance sales, New Year teaser content. High consumer activity as people spend Christmas money.",
    leadDays: 2,
  },
  {
    name: "New Year's Eve",
    eventType: "commercial_event",
    month: 12, day: 31,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "EG", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Year-end reflection and gratitude. Countdown content, year highlights, thank-you-to-customers messaging. Build excitement for January offers.",
    leadDays: 5,
  },
  // ─── PAN-AFRICAN / GLOBAL AWARENESS ─────────────────────────────────────────
  {
    name: "Africa Day",
    eventType: "awareness_day",
    month: 5, day: 25,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "EG", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Pan-African pride. Celebrate African innovation, culture, and business. Works for any brand with a 'proudly African' story. High engagement among African professionals.",
    leadDays: 5,
  },
  {
    name: "World Mental Health Day",
    eventType: "awareness_day",
    month: 10, day: 10,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Wellness, rest, and self-care messaging. Growing awareness in Nigeria especially among young urban audiences. Good for lifestyle, health, and HR brands.",
    leadDays: 3,
  },
  {
    name: "World Entrepreneurship Day",
    eventType: "awareness_day",
    month: 11, day: 21,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate Nigerian entrepreneurs and SME hustle. Founder stories, business tips, motivational content. Very high engagement in Nigerian business communities.",
    leadDays: 5,
  },
  {
    name: "International Day of African Child",
    eventType: "awareness_day",
    month: 6, day: 16,
    isFloating: false,
    countries: ["NG", "KE", "GH", "ZA", "SN"],
    continent: "Africa",
    religions: [],
    contentAngle: "Education, youth empowerment, and future-of-Africa narratives. CSR and brand purpose content. Strong for education, tech, and NGO-adjacent brands.",
    leadDays: 3,
  },
  {
    name: "Ramadan Start",
    eventType: "awareness_day",
    month: 3, day: 1,
    isFloating: true,
    floatingRule: "First day of Ramadan - lunar calendar, moves each year. Typically February-April. Always verify actual date.",
    countries: ["NG", "KE", "SN", "EG"],
    continent: "Africa",
    religions: ["Muslim"],
    contentAngle: "Ramadan Kareem messaging. Respect the fasting period - avoid food/drink heavy imagery during the day. Night-time and suhoor content performs well. Modest, respectful tone throughout.",
    leadDays: 5,
  },
  {
    name: "Small Business Saturday Nigeria",
    eventType: "commercial_event",
    month: 11, day: 29,
    isFloating: true,
    floatingRule: "Saturday after Black Friday",
    countries: ["NG", "GH"],
    continent: "Africa",
    religions: [],
    contentAngle: "Celebrate and promote Nigerian SMEs. Community shopping, support-local messaging, personal brand stories. Counterbalances big-brand Black Friday noise.",
    leadDays: 7,
  },
];

async function seed() {
  console.log(`Seeding ${events.length} global calendar events...`);

  await db.delete(calendarEventsTable);
  console.log("Cleared existing calendar events.");

  for (const event of events) {
    await db.insert(calendarEventsTable).values(event);
    console.log(`  + ${event.name}`);
  }

  console.log(`\nDone. ${events.length} events seeded.`);
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
